### ISSUE TITLE
[UWP] DownloadFile does not initialize common properties when resuming

### ISSUE THREAD

**Issue by bdurrer** [SimonSimCity/Xamarin-CrossDownloadManager#104]
When the [DownloadFileImplementation](https://github.com/SimonSimCity/Xamarin-CrossDownloadManager/blob/1da1241d941d611ca97b19ff784ff2fe3ed875f8/DownloadManager/Plugin.DownloadManager.UWP/DownloadFileImplementation.cs#L106) is initialized with a `DownloadOperation`, it does not set the Url and Header properties (iOS does, Android sets the Url). It might not be required for the DLManager, but it makes identifying resumed downloads hard/impossible.

I don't know if the headers can be restored, but at least the Url is accessible as `downloadOperation.RequestedUri`

**Comment by SimonSimCity** [comment]
I had a very hard time trying to get a scenario where I needed to resume the downloads. Since Windows Mobile was discontinued, I didn't bother.

If you see the need for your project, you're highly encouraged to create a PR. I'll support you as far as I can, but it takes too much time for me as of now to set up a working windows environment to test this.

Feel free to add any data here that could help others getting around the same issue.
