### ISSUE TITLE
When i download videos In iOS Download Notification is not viewed

### ISSUE THREAD

**Issue by Nagendra574** [SimonSimCity/Xamarin-CrossDownloadManager#115]
1.On Downloading the video In iOS, Download Notification is not viewed.

**Platform:** 
- [x] iOS

**Comment by SimonSimCity** [comment]
I didn't integrate a notification on iOS devices ... Did I miss out on something?

**Comment by Nagendra574** [comment]
Yes. We observed that Download Notification perfectly working in Android devices. But its not working iOS devices. So, can you please help us how can we achieve Download Notification in iOS devices using Xamarin Forms.
Thanks for your help.

**Comment by SimonSimCity** [comment]
I haven't worked with Xamarin Forms, so I can't help you much here.

If you know how to set up a notification, you can register a handler for the event by passing an extended version of `UrlSessionDownloadDelegate` into the constructor of the iOS version of the download manager - this should help you getting on your way for a device specific implementation. You can also remove the native notification shown on Android and create something custom for both devices, this might be the better way anyways in terms of UX.

I'll close this because it's not something this plugin will solve, but rather a request for an example. If somebody sends in a PR I'll have a look at it and merge it.

**Comment by Nagendra574** [comment]
HI,
    I don't  have an experience in IOS as well as swift please give the
related example or alternative suggestion .

Thanks in advance
