### ISSUE TITLE
Downloading without internet

### ISSUE THREAD

**Issue by grayter1** [SimonSimCity/Xamarin-CrossDownloadManager#118]
I have implemented http server on raspberry which has own wireless network without internet access. I would like to transmit file via http but I can't - unless I connect raspberry to internet. I tried to debug but really don't know where problem occur. Raspberry server cannot have internet access - it is my client wish. Can you help me?

**Comment by SimonSimCity** [comment]
Well, since this package is just a wrapper for the native solution given by either of the OSes, I guess you should look it up in one of the forums of either iOS or Android - depending on which platform you're facing the problem.

Closing this because it's about the internals of a native implementation I'm using here.
