### ISSUE TITLE
Adding to the queue and starting the download

### ISSUE THREAD

**Issue by Ruddy2007** [SimonSimCity/Xamarin-CrossDownloadManager#18]
I am going to be using this for a project that will download 1000+ files. I would like to add each of the files into the queue and then start the downloader. Is there a way I should handle this?

As `IDownloadManager.Start() ` accepts a `IDownloadFIle` I'm not sure how to start the download after creating the queue. 

Any help would be great.

**Comment by SimonSimCity** [comment]
Hi, Ruddy

The concept behind this, is that the DownloadManager on each of the platforms are services, running in the background. By fetching your instance of IDownloadManager for the first time, you hook it up to the native DownloadManager. That's also when the Queue is filled with the downloads, currently running (remember, on iOS downloads will continue if your app is closed or crashed and will reopen it when all of them finished).

As these native DownloadManagers do not have a native method to start a number of downloads, you'll have to loop over all these files and call `IDownloadManager.Start()` and provide them the instance of `IDownloadFile`, you created by calling  `IDownloadManager.CreateDownloadFile()`.

Since I have not created a possibility to disable the default download-notification on Android, you may will see a dozend of notifications popping up when starting your 1000+ downloads ...

https://developer.android.com/reference/android/app/DownloadManager.Request.html#setNotificationVisibility(int)

Does this answer your question?

**Comment by Ruddy2007** [comment]
@SimonSimCity I see, that does make sense. Thanks for your fast reply.

Another one for you if you don't mind!

I am trying to use this all from Xamarin forms. How can I do `PathNameForDownloadedFile` for a PCL? Again i'm not sure how to handle this. Is this possible or do I have to handle this from the IOS side (trying to get as much of this working on Forms).

**Comment by SimonSimCity** [comment]
Please create a new issue next time. People, searching a solution for that one won't look into this issue.

It should work if you set the property `Plugin.DownloadManager.Current.PathNameForDownloadedFile` to the desired destination. I saw that there's a PCL storage plugin - maybe it's a good way to use it in combination with mine.

If not, you could also set it by compiler-flags: https://developer.xamarin.com/guides/cross-platform/application_fundamentals/building_cross_platform_applications/part_4_-_platform_divergence_abstraction_divergent_implementation/#Using_Conditional_Compilation

**Comment by Ruddy2007** [comment]
I seem to be running into some problems using the plugin for this many files.
 
This is how I have set it up and it seems to work up till 100 files then seems to redownload the same file and then stop. Any pointers? 

```
// Test to get the file
			var dlm = CrossDownloadManager.Current;
			var path = DependencyService.Get<SharedCode>().GetDocumentsPath();

			// Get all data
			var allData = App.Database.GetListOfMissingFiles();

			dlm.Queue.CollectionChanged += (object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e) =>
			{
				Debug.WriteLine(e);
			};

			foreach (var d in allData)
			{
				var file = dlm.CreateDownloadFile(d.uri);
				dlm.PathNameForDownloadedFile += (Plugin.DownloadManager.Abstractions.IDownloadFile arg) =>
				{
					return Path.Combine(path, d.filename);
				};

				dlm.Start(file);
			}
```

**Comment by SimonSimCity** [comment]
The method, passed to the property `PathNameForDownloadedFile`, is a method that should be set `before` the first DownloadFile is created. There's no need to create it again once it has been specified.

In order to have it working on iOS, you need to set it when your app is initialized, not when you start downloading the file. The system otherwise won't save the file if your app fells asleep and wakes up later.

There may be other platform dependent limitations ...

As you were talking about 1k+ files, I already thought that this implementation may is the wrong way to go. The native DownloadManagers, that this extension is using, is designed for downloading large files in the background. If you really need to download that much files, those are not large, am I right? So, you should look for an implementation that's not using the native download manager.
