### ISSUE TITLE
[Android] Include permission in manifest automatically

### ISSUE THREAD

**Issue by jamesmontemagno** [SimonSimCity/Xamarin-CrossDownloadManager#19]
A nice pattern is if your plugin requires a permission you can add an assembly attribute:

https://github.com/jamesmontemagno/Xamarin.Plugins/blob/master/Media/Media/Media.Plugin.Android/Properties/AssemblyInfo.cs#L18-L19

**Comment by SimonSimCity** [comment]
Thanks for this information. Currently it depends on your implementation if you need the permission `WRITE_EXTERNAL_STORAGE` - that's why I chose to only note it down in the manual.

Even if it's the recommended way to write to a location outside the app (what requires the permission), you can download the file to a temporary directory by not providing any destination directory. But I'll check if the permission is set when you try to start a download to a specified destination in #20.

**Comment by jamesmontemagno** [comment]
Ah gotcha, I didn't realize that it was optional :) Good to know.
