### ISSUE TITLE
[iOS] DownloadManager doesn't work

### ISSUE THREAD

**Issue by larghi-truelogic** [SimonSimCity/Xamarin-CrossDownloadManager#23]
I've a XF project for iOS and Android. The Android version is working without problem. The iOS version doesn't work, doesn't trigger any callback any action whatsoever.

This are my files:

- [Info.plist](https://gist.github.com/larghi-truelogic/9cb95bb1a38219943b856a5293b19960)
- [AppDelegate.cs](https://gist.github.com/larghi-truelogic/0bdb0d34d3024ce387b310a476f79a5f)
- [Where I'm calling the library](https://gist.github.com/larghi-truelogic/86e18f6874bb82188f01304af951572f)

Since a couple of days that I'm trying to make this library work on iOS I'm running the app in a simulator since that I don't have a phisical device. If you can take a brief glimpse to the app code and tell me if something seems wrong, I'd appreciate it.

If you need any other data please tell me.

**Comment by SimonSimCity** [comment]
Are you downloading your data from an insecure connection (http instead of https)? If yes, you'd need to make sure, you added the domain (inkl subdomain) to your Info.plist file (see: https://github.com/SimonSimCity/Xamarin-CrossDownloadManager/commit/ebcf1a591429d7282e7eb448ded6de83f883de97#diff-426319ec884bb2430b965a63dd37bd18)

For debugging, I'd register your own `UrlSessionDownloadDelegate` (https://github.com/SimonSimCity/Xamarin-CrossDownloadManager/blob/master/Sample/iOS/ViewController.cs#L16), implement all methods and set breakpoints there. Specially at the `DidCompleteWithError` method.

Does that help?

**Comment by larghi-truelogic** [comment]
Yes in both in my `Ìnfo.plist` you can check that I'm allowing insecure connections. And in my `AppDelegate` as you can see I'm using an `ExtendedUrlSessionDownloadDelegate.cs`. There's no way of debbugin the library so I can check step by step. The weird thing is that there's no error log message related to the library, once that I executed `downloadManager.Start(file)` or `CrossDownloadManager.Current.Start(file)`, that is, the app doesn't crash but anything happens. I'm running this in a simulator maybe that's why?

**Comment by larghi-truelogic** [comment]
Sorry It was the simulator I tried in an iPhone 6s device and It worked perfectly! Sorry for wasting an issue.

**Comment by SimonSimCity** [comment]
Nice to know ... Haven't had those kind of problems with the simulator before ... but if it works on a real device, that's what counts, right? :wink:
