### ISSUE TITLE
[Android] Can not download large files

### ISSUE THREAD

**Issue by VitaliiLytvynov** [SimonSimCity/Xamarin-CrossDownloadManager#33]
Status is always in a running state but a file does not downloading.

Tried also your example with this download link: "http://www.speedtestx.de/testfiles/data_256mb.test" (256mb)

Does not work, same behaviour.

**Comment by SimonSimCity** [comment]
Have you tried the sample I put in this project?

Please give it a try again. I've updated quite much on the Android implementation.

If it still turns out to have the same result, please tell me what version of Android you have.

**Comment by VitaliiLytvynov** [comment]
2.3.7 - Can install app, but it crashes in the start
4.1.1 - Does not work
4.2.2 - Does not work
4.3 - Does not work
4.4.4 - Does not work
5.0.0 - Works well
5.1.0 - Works well
6.0.0 - Works well

**Comment by SimonSimCity** [comment]
For the Android `2.3.7`, the library is built against the SDK in version 16, but to run it on Android `2.3.7`, you'd need to take it down to v10 at least. The main reason I've done this is because of the method `SetAllowedOverMetered()`, which is first available in v16. See https://developer.android.com/reference/android/app/DownloadManager.Request.html#setAllowedOverMetered(boolean)

If you want, you can write a pull-request where you check the SDK version and use this or `SetAllowedOverRoaming()` for lower versions. Feel free. I'd gladly accept it :wink:

I'll take a look at why it doesn't work for you on 4.x.x ...

**Comment by SimonSimCity** [comment]
I've now done quite some changes to how error-reporting works on the Android version of this Package.

Downloading the smaller version (up to 100mb) works quite fine on all versions you mentioned, but as soon as you try the 265mb version, it seems to be quite buggy. Here are the results I had:

SDK Version | Android Version | Result
---------------|-------------------|----------
16 | Android 4.1.1 (simulator) | reported as [Pending for download](https://github.com/SimonSimCity/Xamarin-CrossDownloadManager/blob/master/DownloadManager/Plugin.DownloadManager.Abstractions/IDownloadFile.cs#L16) - as if it would need an extra permission ...
16 | Android 4.1.2 (Sony Xperia S) | `Status = Failed`<br>`StatusDetails = "Error.InsufficientSpace"`<br>Even if the settings tell me that I have 618MB free internally and 1.09GB externally
19 | Android 4.4.2 (simulator) | `Status = Failed`<br>`StatusDetails = "Error.InsufficientSpace"`<br>Even if the settings tell me that I have 4.70GB free
22 | Android 5.1 (simulator) | works as expected

If I open the Download app on either failing unit, the system seems to retry downloading this item as long as I do not abort it. You see it switching from `Running` to `Failing` - again and again.

I guess that the Android Version 4.x had some bugs in their implementation of the `DownloadManager`.

As the `DownloadManager` on Android is just a service, running in the background, which I could also write yourself (and some developers also encourage you to do it), my suggestion is to follow #34 and do our own managed downloads in the background.

If you see anything I could do, excepted from #34, please tell me. Otherwise I'll close this issue here, as it's a bug in the Android API (at least, that's how it seems to me).

If you have the time to start on #34, I'd appreciate it and support you. As of now, it doesn't seem that I'll have the time to take it up.

**Comment by SimonSimCity** [comment]
Just looked into it, because I just couldn't get over it ...

There are some commits on the Android platform for this service, that seem to be related to this: https://github.com/android/platform_packages_providers_downloadprovider/commits/master/src/com/android/providers/downloads/DownloadThread.java Specially the one at Feb 6, 2014 ...
