### ISSUE TITLE
[Android] Notification area not cleaned

### ISSUE THREAD

**Issue by candidodmv** [SimonSimCity/Xamarin-CrossDownloadManager#37]
Hi, 
Congrats by this amazing plugin. But, there is some option to set for that after complete download not clean form notification area? keep that file name for that case the user wants open externally another moment, even that downloader app was closed. This will be very useful, because at moment after download is finished the manager remove that notification from message area. 

Thanks so much!

**Comment by SimonSimCity** [comment]
Thanks for the response @candidodmv.

I do not fully understand what you mean here.

On Android, the download is handed over to the locally implemented Download service, provided by Android itself. It shows all downloads (despide the source) in a single notification and just notifies the user if all those downloads are finished. If you vote for that this plugin should implement it's own download-manager to gain more control over the notification shown, please add a vote to #34.

If it is about something else, please explain it a little more detailed.

**Comment by candidodmv** [comment]
No, it is exactly you said. The question is that after the plugin Xamarin-CrossDownloadManager pass to Android Download service the responsibility of download the file, there are some other options even of the URL of the file, such as configurations like that a flag to clean the notification at the notification area on Android, because, if I do download with other Android App for example with Chrome, even after the download is finished keep a message showing that file was successfully or has error of that file I was downloaded.
Thanks so much, by the way, i did vote to create implement it's own download-manager.

**Comment by SimonSimCity** [comment]
I'd also vote for a self-written implementation of that one ... but as of now, I don't have the needed time to do it.

If you want to get to the download-handler of the file, you could try to get it yourself:

`(Android.App.DownloadManager)Application.Context.GetSystemService (Context.DownloadService)` gives you the native `DownloadManager`. If you then, on Android, run over the queue and cast each instance to `Plugin.DownloadManager.DownloadFileImplementation`, you'll be able to get to the `Id` that you can use to get to the pointer you need to set the flags you need. As of now, this is the only way to do it, since I see no reason making this available cross-platform, since the other systems do not support it ..

Does this fulfill your requirements?

**Comment by candidodmv** [comment]
Yes, if there is some property that filfull this configuration, this approach will works!
Thanks
