### ISSUE TITLE
why not add an async support

### ISSUE THREAD

**Issue by cjw1115** [SimonSimCity/Xamarin-CrossDownloadManager#41]

**Comment by SimonSimCity** [comment]
The download-manager is also meant for bigger downloads. Using an async approach sounds like you want to handle many small downloads.

Since all of the download-managers are build to continue after your app has been destroyed, using async methods do not work.

What's your reason to use async methods?

**Comment by cjw1115** [comment]
Thanks.
I try to finish the uwp version of your Download-Manager,but in the uwp,almost all apis are async method in storage and network. I can't use the interface in the current version.(I am in lower level about coding.)
So I'd like sugest to add an async support that like the BackgroundDownloader in uwp.Perhaps we will get a better experence in coding.

**Comment by SimonSimCity** [comment]
@cjw1115 Ok, it now sounds completely different to what I thought in the beginning. Since you want to implement the download-manager for UWP, I suggest you should clone this repository and start off with a reading here: https://msdn.microsoft.com/en-us/windows/uwp/networking/background-transfers

I, sadly, neither have Windows on my laptop, neither do I have a windows-phone. So I can't test or prove anything you send in, but I think you'll get it done well.

The download-managers on all platforms are services (maybe you call it tasks ... maybe something else ...) that are just downloading files to a specific destination and inform your app when it's finished. The load of downloading, retrying on failure etc. is so on a native service, which makes everything quite stress-less for me :wink:

I will close this in favor to #8. Please continue there.
