### ISSUE TITLE
Display Notification when DownLoad finishes

### ISSUE THREAD

**Issue by GeetSh** [SimonSimCity/Xamarin-CrossDownloadManager#57]
How can one display Notification/Alert when DownLoad finishes? Moreover, I want to display Activity Indicator, till the file is downloaded in Listview row.

**Comment by SimonSimCity** [comment]
Since you're talking about activities, I guess you're talking about Android only, am I right?

**Comment by GeetSh** [comment]
Thanks for Replying. I am working on Cross Platform. So, want to implement for Android & Ios.

**Comment by SimonSimCity** [comment]
Android has a notification, that you might want to disable (please check the solution in #52, which I'll just merge if the author of the issue doesn't respond) or configure to only show when the download is finished.

In order to show some custom notification, just subscribe to the collection ( `CrossDownloadManager.CollectionChanged += (sender, e) => {}` after you've added the download and you're good to go. this will be triggered when the collection changes, which includes a stopped, canceled, finished download or a new download.

For the activity for each download, you'd have to subscribe to it's propertyChange-listener `IDownloadFile.PropertyChanged += (sender, e) => {}`. You'll either get to these instances by looping over `CrossDownloadManager.Queue` or by it's `CollectionChanged` event.

Does this answer your question?

**Comment by GeetSh** [comment]
I had checked the sample project, it's for Android. But I am trying to display message(in Cross Platform) when Download completed.

**Comment by SimonSimCity** [comment]
And because iOS doesn't have something built in, I'd disable it for Android (because it's for all apps using the download-manager) and build my own notification for it.

If you think you found something pretty good, you can create a pull-request and add it to this repo.

**Comment by GeetSh** [comment]
Thanks Simon. In Portable project, I had used CrossDownloadManager.CollectionChanged and things worked out.

**Comment by chinni-nag** [comment]
@GeetSh  Can you please tell me how to show the notification for Download finished for Ios side, Android working fine. Please let me know how to do that. Thanks.
