### ISSUE TITLE
ios fail start download

### ISSUE THREAD

**Issue by helmishariff** [SimonSimCity/Xamarin-CrossDownloadManager#68]
When I try to start download. It failed. From sample project.

```
[DownloadManager] Add -> New items: 1 at -1 || Old items: 0 at -1
Thread started:  #8
FAILED
Canceled.
FAILED
[DownloadManager] Remove -> New items: 0 at -1 || Old items: 1 at -1
```

**Comment by SimonSimCity** [comment]
@helmishariff please tell me more about it ... I haven't had this and I personally don't have access to an iPhone or iPad anymore.

Does it happen in the simulator or real device? What iOS version is installed and what physical device is it?

**Comment by helmishariff** [comment]
I have tried run the sample code. It can't be installed on simulator or iPhone.
Emulator: IOS 11
iPhone 6 IOS 11

**Comment by SimonSimCity** [comment]
But that's a different bug. What do you get for the simulator though?

And what device was the first log from?

And please tell me a bit more next time ... it's like I just get the answer for exactly what I ask for and nothing more, which makes me just ask more questions or drop it because it's too much work getting the necessary information.

**Comment by helmishariff** [comment]
I got this message on simulator: error MT0117: Can't launch a 32-bit app on a simulator that only supports 64-bit apps (iPhone 8).

So, I created a test project an install the plugin using nuget. But when I try to start download, I got this message in output log.
[DownloadManager] Add -> New items: 1 at -1 || Old items: 0 at -1
FAILED
Canceled.
FAILED
[DownloadManager] Remove -> New items: 0 at -1 || Old items: 1 at -1

**Comment by SimonSimCity** [comment]
@helmishariff Have you tried to install the sample app on iOS 10? Can you also tell me more about your development environment? Can you set up your own project importing my library - not using`nuget`, but by a project-import?

I can't see where this message should come from because my project is compiled for `x86` and `x86_64` processors.

**Comment by SimonSimCity** [comment]
I'll update to Mac OS High Sierra and can first then start testing on iOS 11 ... until then, I'm fully reliant on you to test it, see into it and help me finding the source of the problem.

**Comment by helmishariff** [comment]
Samples working find on my another machine MacOS 10.11.6 with simulator iOS 10.2.

**Comment by SimonSimCity** [comment]
@helmishariff I've finally managed to reinstall my mac and install the latest version of Mac OS (10.13.3) and could perfectly run the sample app I have on `iOS 11.2` on an iPhone 8. Were you able to get it running in the meanwhile?

**Comment by SimonSimCity** [comment]
Closed due to lack of feedback ...
