### ISSUE TITLE
[Android] Is it possible to make download notification optional?

### ISSUE THREAD

**Issue by BtrJay** [SimonSimCity/Xamarin-CrossDownloadManager#71]
Hi @SimonSimCity ,

When download starts, it shows the progress in notification center.

This isn't actually an issue. However, I don't think every user would like to see that so it would be good to make it optional in abstraction layer? 

#Steps to reproduce

1. Start downloading a file in Android devices

2. The progress is showing in notification center

If you would like me to create a pull request for that, please let me know.

Kind Regards,

Jay Sim

**Comment by BtrJay** [comment]
![image](https://user-images.githubusercontent.com/22138279/31160366-9421141a-a91b-11e7-8bda-61db001a7104.png)

**Comment by SimonSimCity** [comment]
I rather keep it like that and let you decide if you want to do something that differs from the default Android settings - mainly because it's an Android default.

Everyone can disable it if he doesn't want this behavior ... Same with that every download is added to the `Download` app. You can keep it, and it's Android's default to do so, but you're free to change it at any time if you want using the plugins configuration.

**Comment by BtrJay** [comment]
Thanks @SimonSimCity ,

Is there a way to disable this notification in the plugins configuration?

If so, how could I do that? 

If it needs to be a new task/feature, I could create a PR for that.

Regards,

Jay Sim

**Comment by SimonSimCity** [comment]
See #61

**Comment by BtrJay** [comment]
Thank you for your help @SimonSimCity
