### ISSUE TITLE
Please Tell Where is the downloaded file located 

### ISSUE THREAD

**Issue by cse1sp14cs109** [SimonSimCity/Xamarin-CrossDownloadManager#72]
I was able to run you project and download was successful  

> But when i searched my file inside my  mobile it is not save

### Steps to reproduce
Looked at your issues #10 and #17

1. I installed plugin for all project even enabled write, Network Access , Internet permission for android
1. I installed PCl storage too, but did not find file inside my phone storage

**Platform:** 

- [X] Xamarin forms Android

**Device:** 

- [X] Real device: Samsung GT-N700(Android 4.4 ApI level 19)

**Comment by cse1sp14cs109** [comment]
Sorry I was a Beginner At last i enabled
  CrossDownloadManager.Current.PathNameForDownloadedFile = new Func<IDownloadFile, string>(file =>
            {
                string fileName = Android.Net.Uri.Parse(file.Url).Path.Split('/').Last();
                return Path.Combine(ApplicationContext.GetExternalFilesDir(Android.OS.Environment.DirectoryDownloads).AbsolutePath, fileName);
            });
And My file were inside
This PC\GT-N7100\Phone\Android\data\com.example.download_example\files\Download
Is this the correct solution ?

**Comment by SimonSimCity** [comment]
@cse1sp14cs109 Please keep in mind that you need to set the file destination immediately after starting your app. This is because the different OS have quite different implementations in their native download-manager.

Did this already solve this issue?

*Edit:* I've taken advantage of the possibility and updated your markdown to make it easier readable ...

**Comment by SimonSimCity** [comment]
Closed due to lack of feedback ...
