### ISSUE TITLE
A simple save-as function?

### ISSUE THREAD

**Issue by large** [SimonSimCity/Xamarin-CrossDownloadManager#78]
This isn't a issue, but a feature/dunno-how request ;)

If I have a download link like http://somelink.com/filegenerator/wefokwjefljk32l4lzzq and wants to save it with a custom filename, like "filename.txt". Cannot find anywhere to trigger that, by using default download location. Probably can set it by using PathNameForDownloadedFile ???

But a easier implementation is to add a function like:
void Start (IDownloadFile file, bool mobileNetworkAllowed = true, string sSaveAs = "");
Then add in IDownloadFile a "Filename" here field here. So you know what is was stored as.

Regards Large

**Comment by SimonSimCity** [comment]
The right place for this would be the lambda expression `PathNameForDownloadedFile`. Due to some of the implementations, the behavior, when this value is called out, is quite different. On some platforms it's needed when starting the download, whereby some other require it when the download is finished.

Since I wanted to keep the footprint (and thereby also the possibility of errors) on a minimum, I chose not to include a key-value storage which I would need in order to store these values and pick them up later when they're needed.

If you want, feel free to wrap this package with e.g. `Akavache` or maybe also a package that would use the native key-value stores instead. I'd be glad to assist you there.

If you need any assistance in order to create an example, please ping me and I'll see how I can manage it, but please bare with me that the bugs, reported here, currently have a higher priority. Pull requests are always welcome and I'll definitively help you getting it in.
