### ISSUE TITLE
UWP Support

### ISSUE THREAD

**Issue by deepakSP** [SimonSimCity/Xamarin-CrossDownloadManager#8]
any chance of adding uwp support ??

**Comment by SimonSimCity** [comment]
If you create a prototype of how an implementation could look like, I'd be glad to accept a pull-request or help you along in every way I can.

I have an windows environment at hand, but no sample application where I could test an implementation with.

**Comment by deepakSP** [comment]
i have added BackgroundDownloader in my uwp project so i will try to fork n implement.If all good wiill create new pull request

**Comment by SimonSimCity** [comment]
@deepakSP What progress have you made until now? Is there anything I can assist you with?

**Comment by SimonSimCity** [comment]
Just found an interesting link to this topic: https://msdn.microsoft.com/en-us/windows/uwp/networking/background-transfers

**Comment by SimonSimCity** [comment]
@deepakSP, @Magic73, @adamashton, @cjw1115 I've now taken the time and wrote an implementation. Please check it out and leave some comments.

I met some restrictions concerning the destination of the downloaded files. Could you please check out this repo, read through the comments in the sample and help me finishing the implementation?

**Comment by Magic73** [comment]
I'm going to do some test, and in case I will give to you some feedback/changes.

**Comment by muhaym** [comment]
Hi, I wish to contribute to the UWP part. Just to get started, can you please list out the issues and challenges faced by UWP project currently?

**Comment by SimonSimCity** [comment]
@muhaym Thanks for your response.  I personally haven't used this library on UWP for quite a while now, so I'd myself have to dive into the code and check it out once more. Feel free to just clone it an run the UWP project in the sample-folder.

I can just remember having some troubles to define the file-destination when creating the download. Here's a comment that I wrote because the system restricted me when I tried to save on a custom location: https://github.com/SimonSimCity/Xamarin-CrossDownloadManager/blob/develop/Sample/UWP/MainPage.xaml.cs#L33
I remember that I used a directory-picker and got an object back, but was (due to the current infrastructure of the library) only able to share a string as absolute path to the folder. When trying this, the plugin failed to write to this directory later, because the permissions to save to this folder were bound to the object. The reason here is, that I need the permission at any time, even if the app crashed and you open it. The user won't be happy if I ask for a directory every time he opens the app ...

**Comment by muhaym** [comment]
@SimonSimCity  Thanks. Looking forward to help with my current knowledge :)

**Comment by BtrJay** [comment]
Hi @SimonSimCity ,

Does UWP support the queued download? It seems iOS sample does work but not UWP.

After checking the UWP implementation, I've found that the file has never been added to a download queue for UWP.

Are there updates/fixes for this? I can open the pull request if there aren't

Kind Regards,

Jay

**Comment by SimonSimCity** [comment]
If there isn't any other feedback, I'm going to close this as a limited version for now and call it done.

**Comment by BtrJay** [comment]
Sure, it's done then

**Comment by SimonSimCity** [comment]
@BtrJay What's your opinion on the issue I referenced earlier (https://github.com/SimonSimCity/Xamarin-CrossDownloadManager/blob/develop/Sample/UWP/MainPage.xaml.cs#L33)?

**Comment by SimonSimCity** [comment]
I've just released a new version where UWP is considered fully supported 🎉
