### ISSUE TITLE
[Enhancement] IDownloadFile add on object

### ISSUE THREAD

**Issue by Ruddy2007** [SimonSimCity/Xamarin-CrossDownloadManager#84]
Just a quick one from me.

After a download is complete I want to update my DB table to reflect this, the way I would like to do that is to target the row using its ID but the only value I can use with `IDownloadFile` is the URL. 

It would be nice if when we setup `IDownloadFile` we can have the option to add an object onto it so we can get to that object where ever we want.

Little example of how I see this working below. 

```
        public void SyncAssets()
        {
            var listOfAssets = _databaseService.AllMedia();

            // Asset type is "Media"
            foreach (var asset in listOfAssets)
            {
                IDownloadFile file = _downloadManager.CreateDownloadFile(asset.Url);
                file.AddOn = asset; // Something like this
                file.PropertyChanged += File_PropertyChanged;
                _downloadManager.Start(file, false);
            }
        }

        void File_PropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
        {
            IDownloadFile file = (IDownloadFile)sender;

            if (e.PropertyName == "Status")
            {
                if (file.Status == DownloadFileStatus.COMPLETED)
                {
                    Media media = (Media)file.AddOn;
                }
            }
        }

```

Unless I am missing something the only workaround I see is to give the ID through as a header when setting up `IDownloadFile`.

**Comment by SimonSimCity** [comment]
Only Android actually uses an id per download. In an Android specific environment, you can cast every instance of `IDownloadFile` to `DownloadFileImplementation` which will give you access to the `id` parameter.

The complex part here for me is, that the instances of the classes implementing the `IDownloadFile` interface has to be rebuilt in case your app was suspended and is started up again.

If you don't need the feature of a download continuing even if your app is suspended or your files are very small, this package isn't built for your use-case, and you will be better of if you request the data using `WebClient.DownloadFile` - here's a sample: http://www.csharp-examples.net/download-files/

The goal should always be to find the right tool for the right job and use it in the right way :wink:

If you only have Andorid and want to use my package, I'd note down the id when starting the download and register a property-listener which is triggered when a file is finished. This will aways work because of the `BroadcastReceiver` I've registered for Android: https://github.com/SimonSimCity/Xamarin-CrossDownloadManager/blob/develop/DownloadManager/Plugin.DownloadManager.Android/DownloadCompletedBroadcastReceiver.cs

If you want to use it both for Android and iOS, you'd need to find a way to identify the downloads on the iOS side as well ...

Does this answer the feature-request? 😊

**Comment by Ruddy2007** [comment]
I feel like your selling yourself short here. To my knowledge there isn't another downloader like this, cross platform and it works!

I needed a quick way to download files for iOS, Android and Windows and this ticks all the boxes and does it well. The feature to continue downloading after the app is suspended is more of a option (to me). I need my app up to date at all times (every time you resume the app), so I will stop and clear the download list and repopulate it as that suites my needs. 

In regards to this feature request I can see where the problem lies (rebuilding the IDownloadFile) but as I do not require this feature it shouldn't be a problem for me. Maybe it would be worth me forking your repo and mound this into what I need? Would that be a better option?

**Comment by SimonSimCity** [comment]
Read your question again and again ... here are some ideas that keep popping up in my mind when I hear it:

1. Use Akavache as an extension to this library and register on the different download stati
1. Replace this by the `WebClient.DownloadFile`

For the first of those options you'll still be using this library and use the download-url as a key on Akavache where you store additional data to the downloaded file. This would as well have been what I would've done - I just wanted to avoid an additional unnecessary dependency. If you see other people would might have similar situations, I highly encourage you to publish it yourself as an extension to mine - not as a replacement.

The second option would be a replacement where you do not use the native background download functionality but the one provided in the C# framework. This requires e.g. iOS devices to stay awake while downloading, but it would work entirely without this extension and give you the freedom to do whatever you want. But as I see the demand for battery increasing I bet that also Android will soon follow a similar aggressive strategy as iOS on handling background processes.

As none of these solutions would be built into this library, I'm going to close this issue and leave you with these options. Anyone coming around is very welcome to leave additional comments or suggestions to solve this.

**Comment by Ruddy2007** [comment]
@SimonSimCity Late reply for this but just wanted to say thank you for your time on this matter. I am still using this plugin and I have it working well for what I need it for so thanks again!
