### ISSUE TITLE
Exception: Cannot change ObservableCollection during a CollectionChanged event.

### ISSUE THREAD

**Issue by SimonSimCity** [SimonSimCity/Xamarin-CrossDownloadManager#9]
I lately got an exception on a remove-message within this library ...
Sadly, I don't have the full stack-trace, but it was raised by a collectionChanged trigger ...

That time it happened on iOS.

**Comment by SimonSimCity** [comment]
An advice I got was to use a synchronized version of the collection (https://github.com/CoryCharlton/CCSWE-Libraries/blob/e580b97e2b2c4f17826f268d654813e87d6c99e3/Source/Core/Collections/ObjectModel/SynchronizedObservableCollection%601.cs) or to lock the collection when items are added or removed. We could in addition just give away a copied version of the list (of list only, not a copy of the items in the list). All these are examples I could implement to make it easier. Keep in mind, that the event should then also perform its actions on a copy of the queue.

**Comment by SimonSimCity** [comment]
Can't see this exception rising again ... closing it for now. I'll may reopen it and take a closer look at it when I get it again. Maybe it was just something that was because I ran a bunch of long triggers when the queue changed.

**Comment by SimonSimCity** [comment]
Raised again ...

```C#
System.Collections.ObjectModel.ObservableCollection<T>.CheckReentrancy()
System.Collections.ObjectModel.ObservableCollection<T>.InsertItem(int index, T item)
System.Collections.ObjectModel.Collection<T>.Add(T item)
Plugin.DownloadManager.DownloadManagerImplementation.Start(IDownloadFile i)
```

**Comment by fela98** [comment]
I also get the exception...

I think the problem is that an ObservableCollection is not originally thread safe. The problem occurs for me when there are two different threads accessing and modifying the Queue. When they suddenly try to do it at the same time we get an InvalidOperationException.

Another example of how to implement a ThreadSafe Observable Collection can be found in Robert Frasers answer to this question.
http://stackoverflow.com/questions/23108045/how-to-make-observablecollection-thread-safe
