### ISSUE TITLE
Open downloaded file inside the application

### ISSUE THREAD

**Issue by hashimks** [SimonSimCity/Xamarin-CrossDownloadManager#93]
Hello @SimonSimCity 

I am using the plugin for downloading files from the provided url. I am able to do it, however can you please help me opening and viewing the file simultaneously after the download?

**Comment by SimonSimCity** [comment]
Nice to get some feedback again 😄

In the sample project you can see how to get the URI after a successful download. From there on it's on your side what to do with the file.

* Android: https://github.com/SimonSimCity/Xamarin-CrossDownloadManager/blob/develop/Sample/Droid/MainActivity.cs#L109

I saw that I haven't included any sample on iOS which would return the path. Since I've moved over to other projects I'm not that experienced in Xamarin anymore ... Please ping me if you are struggling with it and I'll see when I have time to get a sample ready.

**Comment by TomONeill** [comment]
It would actually be easier if IDownload included a local file url (which gets set on PathNameForDownloadedFile). This way we can use other plugins, like https://github.com/Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows to open the file easily.

**Comment by tvandegraaf** [comment]
I created a PR that adds a field to the IDownloadFile object. This way you don't have to do obscure things like this:
https://github.com/SimonSimCity/Xamarin-CrossDownloadManager/blob/develop/Sample/Droid/MainActivity.cs#L109

Unfortunately you can't use [FilePicker-Plugin-for-Xamarin-and-Windows](https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows) to open the file, since it has an [issue](https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows/issues/71).

**Comment by SimonSimCity** [comment]
The PR #94 now got accepted and I've just published version 1.4.0 to nuget. This should now allow you to easily get the file destination by the property `DestinationPathName` of every `IDownloadFile` after they reached the status `COMPLETED`.

**Comment by SimonSimCity** [comment]
The PR should've made it much easier. Please report again on this ticket if you're still struggling and I'll reopen it.
